version: "3.9"
services:
    nginx:
        image: nginx:1.20.2-alpine
        container_name: code-academy-nginx
        ports:
            - 8081:80
        volumes:
            - ./php:/home/code-academy/php
            - ./docker-compose/nginx/conf:/etc/nginx/conf.d/
            - ./docker-compose/logs/nginx:/home/code-academy/logs

    # docker run -d -t --name php-test-container -v /Users/kiril/Works/code-academy/PHP:/home/code-academy/PHP -w /home/code-academy/PHP php:7.4.26-alpine3.14
    php:
        image: php:7.4-fpm-alpine3.14
        container_name: code-academy-php
        working_dir: /home/code-academy/php
        # tty: true
        volumes: 
            - ./php:/home/code-academy/php
            - ./docker-compose/php/conf:/usr/local/etc/php/conf.d/
            - ./docker-compose/logs/php-fpm:/var/log/php-fpm
            